# Ques 1:

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [3]:
arr = np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Ques 2:

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it.


Also sort these arrays and print it.

In [38]:
a = [1,3,2,4,7]

b = [5,6,8,11,9]

a_arr = np.asarray(a)
b_arr = np.asarray(b)
c = np.concatenate((a_arr, b_arr))
print(f"Concatenate Array:\n{c}")
print()
print("Sorted Array A")
print(np.sort(a))
print()
print("Sorted Array B")
print(np.sort(b))
print()
print("Sorted Concatenated Array c")
print(np.sort(c))

Concatenate Array:
[ 1  3  2  4  7  5  6  8 11  9]

Sorted Array A
[1 2 3 4 7]

Sorted Array B
[ 5  6  8  9 11]

Sorted Concatenated Array c
[ 1  2  3  4  5  6  7  8  9 11]


# Ques 3:

Write a code snippet to find the dimensions of a ndarray and its size.

In [22]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 5, 6]] )

print("No. of dimensions: ", arr.ndim)
print()
print()
print("Shape of array: ", arr.shape)
print()
print()
print("Size of array: ", arr.size)
print()
print()
print("Array stores elements of type: ", arr.dtype)
print()
print()
print("Array is of type: ", type(arr))

No. of dimensions:  2


Shape of array:  (2, 3)


Size of array:  6


Array stores elements of type:  int32


Array is of type:  <class 'numpy.ndarray'>


# Ques 4:

How to convert a 1D array into a 2D array? 

Demonstrate with the help of a code snippet


Hint: np.newaxis, np.expand_dims

In [21]:
# using expand_dims

arr = [1,2,3,4,5,6,7,8,9,10]
print("1D array")
print()
print(arr)
arr_2d = np.expand_dims(arr, axis=1)
print()
print()
print("2D Array using np.expand.dims")
print()
print(arr_2d)

print()
print()
# using reshape
ar = np.asarray(arr)
arr_reshape = ar.reshape(2,5)
print("2D Array using np.expand.dims")
print()
print(arr_reshape)

1D array

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


2D Array using np.expand.dims

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


2D Array using np.expand.dims

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Ques 5:

Consider two square numpy arrays. Stack them vertically and horizontally.

Hint: Use vstack(), hstack()

In [26]:
a = np.array([[1, 3], 
              [5, 7]]) 
  
b = np.array([[2, 4], 
              [6, 8]]) 

print("Vertical stacking:\n\n", np.vstack((a, b)))
print("\nHorizontal stacking:\n\n", np.hstack((a, b)))

Vertical stacking:

 [[1 3]
 [5 7]
 [2 4]
 [6 8]]

Horizontal stacking:

 [[1 3 2 4]
 [5 7 6 8]]


# Ques 6:

How to get unique items and counts of unique items?

In [32]:
arr = [1,2,2,3,3,4,4,5,6,5,7,8,6,8,9,9]
arr_set = set(arr)
print(f"Unique array:\n{arr_set}")
print()
print(f"Number of unique elements:\n{len(arr_set)}")

# it can be done by using counter method 

Unique array:
{1, 2, 3, 4, 5, 6, 7, 8, 9}

Number of unique elements:
9


In [28]:
arr_set

{1, 2, 3, 4, 5, 6, 7, 8, 9}